[project]
name = ""
version = ""
description = ""
authors = [
    {name = "MatiasPineda", email = "matias.pinedav@gmail.com"},
]
dependencies = [
    "Django>=4.2.5",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

