# Generated by Django 4.2.5 on 2023-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('accounting_balance', models.BigIntegerField(default=0, verbose_name='Saldo contable')),
                ('current_balance', models.BigIntegerField(default=0, verbose_name='Saldo actual')),
                ('line_of_credit_balance', models.PositiveIntegerField(default=0, verbose_name='Saldo de línea de crédito')),
                ('total_charges', models.BigIntegerField(default=0, verbose_name='Total de cargos')),
                ('total_credits', models.BigIntegerField(default=0, verbose_name='Total de abonos')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
